server:
  port: 8102 # 接口服务跑在 8102 端口

api:
  client:
    access-key: 512bb9f11e5d4a99be54e560ba8c5595
    secret-key: ce013ef728099f1c5a4c2102e46c40b2

dubbo:
  application:
    name: api-platform-interface
  registry:
    address: nacos://localhost:8848