server:
  port: 8102 # 接口服务跑在 8102 端口

api:
  client:
    access-key: 94fb2efd037348139b281b67afe41c6b
    secret-key: a6bad40168da9781342522df8085c935

dubbo:
  application:
    name: api-platform-interface
  registry:
    address: nacos://localhost:8848